import { notFound } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { Timeline } from '@/components/timeline'
import { CopyLinkButton } from '@/components/copy-link-button'
import type { Milestone } from '@/lib/schema'

interface PlanRow {
  id: string
  genre: string
  song_count: number
  release_date: string
  posts_per_week: number
  milestones: Milestone[]
  created_at: string
}

function releaseType(songCount: number) {
  if (songCount <= 2) return 'Single'
  if (songCount <= 6) return 'EP'
  return 'Album'
}

function formatRelease(iso: string) {
  return new Date(iso + 'T12:00:00').toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

export default async function PlanPage({
  params,
}: {
  params: Promise<{ uuid: string }>
}) {
  const { uuid } = await params

  const { data, error } = await supabase
    .from('plans')
    .select('*')
    .eq('id', uuid)
    .single()

  if (error || !data) notFound()

  const plan = data as PlanRow

  return (
    <main className="min-h-screen bg-background px-4 py-12">
      <div className="max-w-2xl mx-auto space-y-8">
        {/* Header */}
        <div className="space-y-3">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold tracking-tight">
                {plan.genre} {releaseType(plan.song_count)} Release Plan
              </h1>
              <p className="text-sm text-muted-foreground mt-1">
                Target date: {formatRelease(plan.release_date)} &middot;{' '}
                {plan.song_count} song{plan.song_count === 1 ? '' : 's'} &middot;{' '}
                {plan.posts_per_week}×/week
              </p>
            </div>
            <CopyLinkButton planId={plan.id} />
          </div>

          <p className="text-xs text-muted-foreground/60">
            Hover over any milestone to see the full detail.
          </p>
        </div>

        {/* Timeline */}
        <Timeline milestones={plan.milestones} />

        {/* Footer */}
        <div className="pt-8 border-t border-border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <p className="text-xs text-muted-foreground">
            {plan.milestones.length} milestones &middot; Generated by DropPlanner
          </p>
          <a
            href="/generate"
            className="text-xs text-accent hover:underline underline-offset-2"
          >
            Plan another release →
          </a>
        </div>
      </div>
    </main>
  )
}
